config/routes.rb
Rails.application.routes.draw do
  get 'recipes/index'
  get 'recipes/show'
  get 'recipes/new'
  get "recipes/:id/edit"=>"recipes#edit"
  post "recipes/:id/update"=>"recipes#update"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'likes/index'
  post '/like/:id' => 'likes#like',   as: 'like'
  delete '/like/:id' => 'likes#unlike', as: 'unlike'
  root 'homes#index'
  resources :comments, only: [:index, :show]
  resources :genres, only: [:index, :show, :new, :create]
  #ネストすることによって、どのレシピに対するコメントかが分かるようにしたい。
  resources :recipes, only: [:index, :show, :new, :edit, :create] do
    resources :comments, only: [:create]
    resource :likes, only: [:create, :destroy, :index]
  end
  resources :homes, only: [:index, :new]
  resources :users,only: [:show, :edit, :new]
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :recipes

  def liked_by?(user)
  	likes.where(user_id: user.id).exists?
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
	def index
    	@genres = Genre.all
    end

	def show
		@genre = Genre.find(params[:id])
		@recipes = @genre.recipes
	end

    def new
    	@genre = Genre.new
    end

    def create
    	@genre = Genre.new(genre_params)
    	@genre.save
    	redirect_to genres_path
    end

 private

  def genre_params
  	params.require(:genre).permit(:name)
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/index.html.erb
<div>
<h2>全てのジャンル</h2>
<p>（全<%= @genres.count %>件）</p>
</div>
<div>
	<table class="table table-hover table-inverse">
	<tr>
	<th>ジャンル名</th>
	</tr>
	<% @genres.each do |genre| %>
	<tr>
	<th><%= link_to genre_path(genre.id) do %>
		<%= genre.name %>
	</th>
		<% end %>
		<% end %>
	</tr>
	</table>
</div>

app/views/genres/new.html.erb
<h2>料理ジャンル作成</h2>
<%= form_with model: @genre, local:true do |f| %>
  ジャンル名<%= f.text_field :name %><br >
  <%= f.submit '新規ジャンル作成' %>
<% end %>

app/views/genres/show.html.erb
<div>
<h2>指定したジャンル</h2>
</div>
<div>
  <%= @genre.name %>
</div>

<div>
    <h1>レシピ一覧</h1>
</div>
<div>
<table>
    <tr>
      <th>レシピ名</th>
      <th>ユーザー名</th>
      <th>投稿日</th>
      <th>更新日時</th>
    </tr>
    <% @recipes.each do |recipe| %>
    <tr>
      <th><%= recipe.title %></th>
      <th><%#= recipe.user_name %></th>
      <th><%= recipe.created_at %></th>
      <th><%= recipe.updated_at %></th>
      <!-- いいね機能 -->
    <td>
      <% if recipe.liked_by?(current_user) %>
        <%= link_to recipe_likes_path(recipe), method: :delete do %>
          <span class="glyphicon glyphicon-heart"><%= recipe.likes.count%></span>
        <% end %>
      <% else %>
        <%= link_to recipe_likes_path(recipe), method: :post do %>
          <span class="glyphicon glyphicon-heart-empty"><%= recipe.likes.count %></span>
        <% end %>
      <% end %>
    </td>
      <!-- コメント機能 -->
    <td>コメント数：<%#= home.home_comments.count %></td>
    </tr>
    <% end %>
</table>
</div>
 <!--    <%# @all_ranks.each do |recipe| %>(ランキング機能実装、いいね機能追加する必要あり) -->