config/routes.rb
Rails.application.routes.draw do
  get 'recipes/index'
  get 'recipes/show'
  get 'recipes/new'
  get "recipes/:id/edit"=>"recipes#edit"
  post "recipes/:id/update"=>"recipes#update"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'likes/index'
  post '/like/:id' => 'likes#like',   as: 'like'
  delete '/like/:id' => 'likes#unlike', as: 'unlike'
  root 'homes#index'
  resources :comments, only: [:index, :show]
  resources :genres, only: [:index, :show, :new, :create]
  #ネストすることによって、どのレシピに対するコメントかが分かるようにしたい。
  resources :recipes, only: [:index, :show, :new, :edit, :create] do
    resources :comments, only: [:create]
    resource :likes, only: [:create, :destroy, :index]
  end
  resources :homes, only: [:index, :new]
  resources :users,only: [:show, :edit, :new]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	belongs_to :genre
	belongs_to :user
	has_many :favorites
	has_many :likes, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :liking_users, through: :likes, source: :user

	attachment :photo

	#空データを禁止
	validates :title, presence: true
	validates :item, presence: true
	validates :cooking, presence: true


  def liked_by?(user)
  	likes.where(user_id: user.id).exists?
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
#ユーザーのログイン時のみshow,createの権限を付与するようにする
  before_action :authenticate_user!, only: [:show, :create]

  def index
    search_word = params["recipe"]
  	@recipes = Recipe.where(['title LIKE ?', "%#{search_word}%"]) #検索に関する投稿一覧表示
    @recipe = Recipe.new #新規投稿できるように
    @all_ranks = Recipe.find(Like.group(:recipe_id).order('count(recipe_id) desc').limit(3).pluck(:recipe_id))
  end

  def show
  	@recipe = Recipe.find(params[:id])
	  @recipes = Recipe.where(['title LIKE ?', "%#{@recipe.title}%"])
    @comments = @recipe.comments.order(id: "DESC") #投稿詳細に関連つけてあるコメントの取得
    @comment = Comment.new #新規コメントできるように
    #新しいコメント順にした
  end

  def new
  	@recipe = Recipe.new
    @genres = Genre.all
  end

  def create
  	@recipe = Recipe.new(recipes_params)
    #すでにあるgenreは選択できるようにし、ない物は新規追加させて、保存できる
    genre = Genre.find_or_create_by(name: params[:recipe][:genre_id])
    @recipe.user_id = current_user.id
    @recipe.genre_id = genre.id
    if @recipe.save
      redirect_to recipes_path
    else
      render :new
    end
  end

  def update
    @comment = Comment.find_by(id:params[:id])
    @comment.content = params[:content]
    @comment.save
    redirect_to("/recipes/index")
  end

  def edit
    @recipe = Recipe.find_by(id: params[:id])
  end

private

  def recipes_params
  	params.require(:recipe).permit(:title, :photo, :cooking, :item)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_recipes.html.erb
<%= render 'likes/like', recipe: recipe %>

app/views/recipes/edit.html.erb
<%= form_tag("/recipes/#{@recipe.id}/update") do %>
 <form>
  <div class="form-group">
   <label for="exampleInputEmail1">編集する</label>
   <textarea name="title" class="form-control"><%= @recipe.title %></textarea>
  </div><!--form-group-->
  <button type="submit" class="btn btn-primary">保存</button>
<% end %>

app/views/recipes/index.html.erb
<div class="container">
  <div class="row">
<h2>レシピ</h2>
<p>（全<%= @recipes.count %>件）</p>
</div>

<div class="container-fluid">
  <div class="row sampleRow">
  <% @recipes.each do |recipe| %>
          <!--星評価-->
          <script>
          $('#star-rate-<%= recipe.id %>').raty({
            size: 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            readOnly: true,
            score: "#{recipe.comments.average(:rate).to_f.round(1)}",
          });
          </script>  
        <!--/星評価-->

    <div class="col-xs-12 col-md-6">
      <%= attachment_image_tag recipe, :photo, fill:"40x40", size:"40x40" %>
      <%= link_to recipe_path(recipe.id) do %>
        <%= recipe.title %>
      <% end %>
    </div>

    <div class="col-xs-12 col-md-6">
      <p class="recipes-title"><%= link_to recipe.user.name, recipe.user %></p>
      <p><%= recipe.created_at %></p>
      <h4 class="mb-3">評価：<%= recipe.comments.average(:rate).to_f.round(1) %>点 | <%= recipe.title %></h4>
      <div id="star-rate-<%= recipe.id %>"></div>
      <% recipe.comments.each do |comment| %>
        <p><%= comment.content %></p>
        <% if current_user == comment.user %>
          <%=link_to("/recipes/#{@recipe.id}edit") %>
        <% end %>
      <% end %>
    </div>
  <% end %>
  </div>
</div>
</div>

<div class="container">
  <div class="row">
<h2>おすすすめレシピ</h2>
<div>
  <% @all_ranks.each do |recipe| %>
	<div>
	  <%= recipe.title %>
    <%= recipe.likes.count %>
  </div>
  <% end %>
</div>
</div>
</div>

app/views/recipes/new.html.erb
<div class="container">
  <div class="row">
<h2>料理レシピ</h2>
<%= form_with model: @recipe, local: true do |f| %>
  料理名&ensp;&nbsp;&nbsp;&nbsp;<%= f.text_field :title %><br >
  写真<%= f.attachment_field :photo %><br >
  材料&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= f.text_field :item %><br >
  作り方&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= f.text_field :cooking %><br >
  <fieldset>
  ジャンル&nbsp;<%= f.text_field :genre_id, list: "genre", autocomplete: "on" %><br >
  <datalist id="genre">
  <% @genres.each do |genre| %>
  <option value="<%= genre.name %>">
  <% end %>
  </datalist>
  <%= f.submit 'レシピ作成' %>
  </fieldset>
  <%= link_to 'ホーム画面に戻る', root_path %>
<% end %>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="container">
  <div class="row">
<div>
  <%= link_to recipe_path(@recipe.id) do %>
  <%= attachment_image_tag @recipe, :photo, fill:"40x40", size:"600x400" %><br >
  <% end %>
  <h3>レシピ名</h3>
  <h3><%= @recipe.title %></h3><br ><br >
  <h4>ユーザー名</h4>
  <h4><%= @recipe.user.name %></h4><br ><br >
  <h4>レシピ内容</h4>
  <h4><%= @recipe.cooking %></h4><br ><br >
  <h4>コメント一覧</h4>
  <% @comments.each do |c| %>
    <div>
      <% if c.user.present? %>
        <%= link_to user_path(c.user_id) do %>
        <% end %>
      <%= c.content %><br >
      <%= "#{c.user.name_kanji_sei} #{c.user.name_kanji_mei}" if c.user.present?%><br>
       <!--星評価-->
         <div id="star-rate-<%= c.id %>"></div>
          <script>
          $('#star-rate-<%= c.id %>').raty({
            size: 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            readOnly: true,
            score: <%= c.rate %>,
          });
          </script>
        <!--/星評価-->
    </div><br >
  <% end %>
  <% end %><br >
  新規コメント
  <% if user_signed_in? %>
    <%= form_with(model: [@recipe, @comment], local: true, ) do |f| %>
     <!-- 評価 -->
     <div class="form-group row" id="star">
       <%= f.label :rate,'評価 ', class:'col-md-3 col-form-label' %>
       <%= f.hidden_field :rate, id: :review_star %>
     </div>

     <!-- 評価javascript -->
     <script>
      $('#star').raty({
        size     : 36,
        starOff:  '<%= asset_path('star-off.png') %>',
        starOn : '<%= asset_path('star-on.png') %>',
        starHalf: '<%= asset_path('star-half.png') %>',
        scoreName: 'post[rate]',
        half: true,
      });
    </script>
    <!-- コメント投稿 -->
      <%= f.text_area :content, class: "form-control", rows: 5, placeholder:"まずは投稿してみましょう！投稿してから編集もできます！" %>
      <%= button_tag type: "submit", class: "btn btn-success float-right mt-1" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %><br >
  <div class="index_like_<%= @recipe.id %>">
  いいね<%= render 'likes/like', recipe: @recipe %>
  </div>
</div>

<h2>関連したレシピ一覧</h2>
<div>
<table>
    <tr>
      <th>レシピ名</th>
      <th>ユーザー名</th>
      <th>投稿日</th>
    </tr>
    <% @recipes.each do |recipe| %>
    <tr>
      <th><%= recipe.title %></th>
      <th><%= recipe.user.name %></th>
      <th><%= recipe.created_at.strftime("%Y-%m-%d %H:%M") %></th>
      <!-- いいね機能 -->
    <td class="index_like_<%= recipe.id %>">
      <%= render 'likes/like', recipe: recipe %>
    </td>
      <!-- コメント数確認機能 -->
    <td>コメント数：<%= recipe.comments.count %></td>
    </tr>
    <% end %>
</table>

<div>

</div>
</div>
</div>
</div>