config/routes.rb
Rails.application.routes.draw do
  get 'recipes/index'
  get 'recipes/show'
  get 'recipes/new'
  get "recipes/:id/edit"=>"recipes#edit"
  post "recipes/:id/update"=>"recipes#update"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'likes/index'
  post '/like/:id' => 'likes#like',   as: 'like'
  delete '/like/:id' => 'likes#unlike', as: 'unlike'
  root 'homes#index'
  resources :comments, only: [:index, :show]
  resources :genres, only: [:index, :show, :new, :create]
  #ネストすることによって、どのレシピに対するコメントかが分かるようにしたい。
  resources :recipes, only: [:index, :show, :new, :edit, :create] do
    resources :comments, only: [:create]
    resource :likes, only: [:create, :destroy, :index]
  end
  resources :homes, only: [:index, :new]
  resources :users,only: [:show, :edit, :new]
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
  #item_idとuser_idの組が1組しかないようにバリデーションをしてあげる
  validates_uniqueness_of :recipe_id, scope: :user_id
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :recipe_id_params, only: [:like, :unlike]
  def like
    like = current_user.likes.new(recipe_id: @recipe.id)
    like.save
      flash[:success] = "お気に入りに追加しました。"
  end

  def unlike
    like = current_user.likes.find_by(recipe_id: @recipe.id)
    like.destroy
  end

  def index
    targetLikes = Like.where(user_id: current_user.id).select(:recipe_id)
    @recipes = Recipe.where(id: targetLikes)
  end

  private

  def recipe_id_params
   @recipe = Recipe.find(params[:id])
   @class_name = ".index_likes_#{@recipe.id}"
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if current_user.likes.find_by(recipe_id: recipe.id) %>
  <%= link_to unlike_path(recipe.id), method: :delete, remote: true do %>
        <span class = "iine__button">❤️<%= recipe.likes.count %></span>
    <% end %>
  <% else %>
    <%= link_to like_path(recipe.id), method: :post, remote: true do %>
        <span class = "iine__button">♡️<%= recipe.likes.count %></span>
   <% end %>
<% end %>

app/views/likes/index.html.erb
<div class="container">
  <div class="row">
	<h2>いいねしたレシピ一覧</h2>
	<p>（全<%= @recipes.count %>件）</p>
  </div>
  <div class="row">
	<% @recipes.each do |recipe| %>
	    <%= attachment_image_tag recipe, :photo, fill:"40x40", size:"40x40" %>
	    <%= link_to recipe_path(recipe.id) do %>
		    <%= recipe.title %>
  		<% end %>
	<% end %>
  </div>
</div>

app/views/likes/like.js.erb
$(".index_like_<%= @recipe.id %>").html('<%= escape_javascript(render("likes/like", recipe: @recipe  )) %>');

app/views/likes/unlike.js.erb
$(".index_like_<%= @recipe.id %>").html('<%= escape_javascript(render("likes/like", recipe: @recipe  )) %>');