config/routes.rb
Rails.application.routes.draw do
  get 'recipes/index'
  get 'recipes/show'
  get 'recipes/new'
  get "recipes/:id/edit"=>"recipes#edit"
  post "recipes/:id/update"=>"recipes#update"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'likes/index'
  post '/like/:id' => 'likes#like',   as: 'like'
  delete '/like/:id' => 'likes#unlike', as: 'unlike'
  root 'homes#index'
  resources :comments, only: [:index, :show]
  resources :genres, only: [:index, :show, :new, :create]
  #ネストすることによって、どのレシピに対するコメントかが分かるようにしたい。
  resources :recipes, only: [:index, :show, :new, :edit, :create] do
    resources :comments, only: [:create]
    resource :likes, only: [:create, :destroy, :index]
  end
  resources :homes, only: [:index, :new]
  resources :users,only: [:show, :edit, :new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :recipe

	validates :content, presence: true
	validates :rate, numericality: {
		less_than_or_equal_to: 5,
		greater_than_or_equal_to: 1
	}, presence: true


end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :recipe
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :recipes

  def liked_by?(user)
  	likes.where(user_id: user.id).exists?
  end
end

app/models/home.rb
class Home < ApplicationRecord
	belongs_to :user
	has_many :likes, dependent: :destroy
	has_many :liking_users, through: :likes, source: :user
	attachment :photo

	def self.search(search)
		if search
			Recipe.where(['content LIKE ?', "%#{search}%"])
		else
			Recipe.all
		end
    end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
  #item_idとuser_idの組が1組しかないようにバリデーションをしてあげる
  validates_uniqueness_of :recipe_id, scope: :user_id
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	belongs_to :genre
	belongs_to :user
	has_many :favorites
	has_many :likes, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :liking_users, through: :likes, source: :user

	attachment :photo

	#空データを禁止
	validates :title, presence: true
	validates :item, presence: true
	validates :cooking, presence: true


  def liked_by?(user)
  	likes.where(user_id: user.id).exists?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :likes ,dependent: :destroy
  has_many :like_stories, through: :likes, source: :home
  has_many :recipes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites
  has_many :favorite_recipes, through: :favorite, source: :recipe

  #空データを禁止,長さの限定
  validates :name_kanji_sei, presence: true, length: { maximum: 50 }
  validates :name_kanji_mei, presence: true, length: { maximum: 50 }
  validates :name_kana_mei, presence: true, length: { maximum: 50 }
  validates :name_kana_sei, presence: true, length: { maximum: 50 }
  #emailの重複,適切な文字のみに制限
  validates :email, presence: true, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i}

  #ブックマーク機能
  def favorite(recipes)
  	favorites.find_or_create_by(recipe_id: recipe_id)
  end

  def unfavorite(recipes)
  	favorite = favorites.find_by(recipe_id: recipe_id)
  	favorite.destroy if favorite
  end
  #いいね機能
  def like(recipes)
  	likes.find_or_create_by(recipe_id: recipe_id)
  end

 def unlike
 	like = likes.find_by(recipe_id: recipe_id)
 	like.destroy if like
 end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
	def index
    	@genres = Genre.all
    end

	def show
		@genre = Genre.find(params[:id])
		@recipes = @genre.recipes
	end

    def new
    	@genre = Genre.new
    end

    def create
    	@genre = Genre.new(genre_params)
    	@genre.save
    	redirect_to genres_path
    end

 private

  def genre_params
  	params.require(:genre).permit(:name)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
  	@recipes = Recipe.all
  	@recipe = Recipe.new
  end

  def new
  	@recipe = Recipe.new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.user_id = current_user.id

  	@recipe = Recipe.new(recipe_params)
  	@recipe.user_id = current_user.id
  	if @recipe.save and @photo.save
  		redirect_to recipe_path(@recipe), notice: "レシピが投稿されました"
  	else
  	  @recipes = Recipe.all
  	  render 'index'
  	end
  end

  def update
  	if @recipe.update(recipe_params)
  		recirect_to recipe_path(@recipe), notice: "レシピが更新されました"
  	else
  		render "edit"
  	end
  end

  def destroy
  	@recipe.destroy
  	recirect_to homes_path
  end

  def search
    @recipes = Recipe.search(params[:recipe])
  end

  private

  def recipe_params
  	params.require(:recipe).permit(:title, :body, :photo, :item)
  end


  def ensure_correct_user
  	@recipe = Recipe.find(params[:id])
  	unless @recipe.user == current_user
  		redirect_to homes_path
  	end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :recipe_id_params, only: [:like, :unlike]
  def like
    like = current_user.likes.new(recipe_id: @recipe.id)
    like.save
      flash[:success] = "お気に入りに追加しました。"
  end

  def unlike
    like = current_user.likes.find_by(recipe_id: @recipe.id)
    like.destroy
  end

  def index
    targetLikes = Like.where(user_id: current_user.id).select(:recipe_id)
    @recipes = Recipe.where(id: targetLikes)
  end

  private

  def recipe_id_params
   @recipe = Recipe.find(params[:id])
   @class_name = ".index_likes_#{@recipe.id}"
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
#ユーザーのログイン時のみshow,createの権限を付与するようにする
  before_action :authenticate_user!, only: [:show, :create]

  def index
    search_word = params["recipe"]
  	@recipes = Recipe.where(['title LIKE ?', "%#{search_word}%"]) #検索に関する投稿一覧表示
    @recipe = Recipe.new #新規投稿できるように
    @all_ranks = Recipe.find(Like.group(:recipe_id).order('count(recipe_id) desc').limit(3).pluck(:recipe_id))
  end

  def show
  	@recipe = Recipe.find(params[:id])
	  @recipes = Recipe.where(['title LIKE ?', "%#{@recipe.title}%"])
    @comments = @recipe.comments.order(id: "DESC") #投稿詳細に関連つけてあるコメントの取得
    @comment = Comment.new #新規コメントできるように
    #新しいコメント順にした
  end

  def new
  	@recipe = Recipe.new
    @genres = Genre.all
  end

  def create
  	@recipe = Recipe.new(recipes_params)
    #すでにあるgenreは選択できるようにし、ない物は新規追加させて、保存できる
    genre = Genre.find_or_create_by(name: params[:recipe][:genre_id])
    @recipe.user_id = current_user.id
    @recipe.genre_id = genre.id
    if @recipe.save
      redirect_to recipes_path
    else
      render :new
    end
  end

  def update
    @comment = Comment.find_by(id:params[:id])
    @comment.content = params[:content]
    @comment.save
    redirect_to("/recipes/index")
  end

  def edit
    @recipe = Recipe.find_by(id: params[:id])
  end

private

  def recipes_params
  	params.require(:recipe).permit(:title, :photo, :cooking, :item)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
	  @user = User.new
	end

	def index
	  @users = User.all
	  @recipe = Recipe.new
	end

	def edit
		@user = User.find(params[:id])
	end

  private

  def user_params
  	params.require(:user).permit(:name, :introdution, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if @book.errors.any? %>
  <div class= "alert alert-warning">
    <h2><%= @recipe.errors.count %> errors prohibited this obj from being saved:</h2>
   <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
     </ul>
  </div>
<% end %> 

app/views/layouts/_header_login.html.erb
<%# ログイン時 %>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to root_path, class: "navbar-brand" do %>
      <img src="/assets/logo.png" alt="" class="logo">
      <% end %>
    </div>
    <div class="collapse navbar-collapse" id="navbarEexample">
      <ul class="nav navbar-nav", style="list-style: none;">
          <li>
            <%= form_tag(recipes_path,:method => 'get', class: "navbar-form navbar-left") do %>
            <%= text_field_tag :recipe, params[:recipe], class: "form-control", placeholder:"気になるレシピを検索!!" %>
            <%= submit_tag 'Search', :title => nil, class: "btn btn-default" %>
            <% end %>
        </li>
      </ul>
       <p class="navbar-text navbar-right">
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "nav-link text-white " %>
      </p>
      <p class="navbar-text navbar-right">ようこそ、
        <%= link_to edit_user_path(current_user), class: "navbar-link" do  %>
                <%= current_user.name_kanji_mei %>
              <% end %>さん
      </p>
      <p class="navbar-text navbar-right">
        <%= link_to "いいねしたレシピ", likes_index_path, class: "navbar-link" %>
      </p>
      <p class="navbar-text navbar-right">
        <%= link_to "レシピ一覧", recipes_path, class: "navbar-link" %>
      </p>
      <p class="navbar-text navbar-right">
        <%= link_to "ジャンル一覧", genres_path, class: "navbar-link" %>
      </p>
      <p class="navbar-text navbar-right">
        <%= link_to "新規レシピ投稿", new_recipe_path, class: "navbar-link" %>
      </p>
    </div>
  </div>
</nav>

app/views/layouts/_header_unknown.html.erb
<%# ログインなし %>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#"><img src="/assets/logo.png" alt="" class="logo"></a>
    </div>
    <div class="collapse navbar-collapse" id="navbarEexample">
      <ul class="nav navbar-nav", style="list-style: none;">
          <li>
            <%= form_tag(recipes_path,:method => 'get', class: "navbar-form navbar-left") do %>
            <%= text_field_tag :recipe, params[:recipe], class: "form-control", placeholder:"気になるレシピを検索!!" %>
            <%= submit_tag 'Search', :title => nil, class: "btn btn-default" %>
            <% end %>
          </li>
      </ul>
      <p class="navbar-text navbar-right">
            <%= link_to '新規登録', new_user_registration_path, class: "nav-link text-white btn btn-outline-light" %>
      </p>
      <p class="navbar-text navbar-right">
            <%= link_to 'ログイン', new_user_session_path, class: "nav-link text-white btn btn-outline-light" %>
      </p>
      <p class="navbar-text navbar-right">
        <%= link_to "レシピ一覧", recipes_path, class: "navbar-link" %>
      </p>
      <p class="navbar-text navbar-right">
        <%= link_to "ジャンル一覧", genres_path, class: "navbar-link" %>
      </p>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LetsStartCooking</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if user_signed_in? %>
        <%= render 'layouts/header_login' %>
        <div class="header-bottom"></div>
      <% else %>
        <%= render 'layouts/header_unknown' %>
        <div class="header-bottom"></div>
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>